### ISSUE TITLE
Beaver не подключается к базе

### ISSUE THREAD

**Issue by SvetlanaVas** [SvetlanaVas/sql#1]
**Шаги по воспроизведению**
1. Установлен Beaver (от имени администратора)
2. База готова к соединению (Plugin ready for connection)
3. При попытке Beaver соединиться с Mysql 
![image](https://user-images.githubusercontent.com/59311062/74505560-8bae2580-4f08-11ea-81dd-3afda7bf68d4.png)
4. При попытке Beaver соединиться с Mysql 8+
![image](https://user-images.githubusercontent.com/59311062/74505664-c87a1c80-4f08-11ea-82e7-2cf0265a3e30.png)

**Comment by ArRomanov** [comment]
У вас, скорее всего, значение true. Измените на false, должно помочь

![Peek 2020-02-14 11-13](https://user-images.githubusercontent.com/23121947/74506262-1b5ccf80-4f1b-11ea-924e-b4d966fefd86.gif)
